export const cards_array = [
    {
        img: 'cake',
        name: 'Торт',
        author: 'Евгений Норенко',
        authorImg: 'person.png',
        time: '30',
        type: ['Десерт'],
    },
    {
        img: 'borsh',
        name: 'Борщ',
        author: 'Евгений Норенко',
        authorImg: 'person.png',
        time: '120',
        type: ['Обед'],
    },
    {
        img: 'avocado',
        name: 'Бутерброды с авокадо',
        author: 'Евгений Норенко',
        authorImg: 'person.png',
        time: '7',
        type: ['Десерт', 'Обед', 'Ужин'],
    },
    {
        img: 'blini',
        name: 'Блины',
        author: 'Евгений Норенко',
        authorImg: 'person.png',
        time: '30',
        type: ['Десерт', 'Завтрак'],
    },
    {
        img: 'franchmeat',
        name: 'Мясо по французски',
        author: 'Евгений Норенко',
        authorImg: 'person.png',
        time: '40',
        type: ['Обед', 'Ужин'],
    },
    {
        img: 'karbonara',
        name: 'Карбонара',
        author: 'Василий Васильев',
        authorImg: 'person.png',
        time: '20',
        type: ['Ужин'],
    },
    {
        img: 'potato',
        name: 'Жареный картофель',
        author: 'Василий Васильев',
        authorImg: 'person.png',
        time: '30',
        type: ['Обед', 'Ужин'],
    },
    {
        img: 'banana',
        name: 'Бананы с йогуртом',
        author: 'Василий Васильев',
        authorImg: 'person.png',
        time: '3',
        type: ['Десерт'],
    },
    {
        img: 'uha',
        name: 'Уха',
        author: 'Иван Иванов',
        authorImg: 'person.png',
        time: '120',
        type: ['Обед'],
    },
    {
        img: 'eggs',
        name: 'Яичница',
        author: 'Иван Иванов',
        authorImg: 'person.png',
        time: '7',
        type: ['Завтрак'],
    },
    {
        img: 'cereal',
        name: 'Овсяная каша',
        author: 'Иван Иванов',
        authorImg: 'person.png',
        time: '10',
        type: ['Завтрак'],
    },
    {
        img: 'cola',
        name: 'Кола',
        author: 'Густаво Фринг',
        authorImg: 'person.png',
        time: '1',
        type: ['Десерт'],
    },
    {
        img: 'free',
        name: 'Картошка фри',
        author: 'Густаво Фринг',
        authorImg: 'person.png',
        time: '7',
        type: ['Обед', 'Ужин'],
    },
    {
        img: 'chicken',
        name: 'Жареная курица',
        author: 'Густаво Фринг',
        authorImg: 'person.png',
        time: '10',
        type: ['Обед', 'Ужин'],
    },
];
